### ISSUE TITLE
Can't Download Reference Protein Sequence Dataset (RPSD) 

### ISSUE THREAD

**Issue by Moo-cow** [carnegie/E2P2#10]
Hi，
I can't get data from 
`Download Reference Protein Sequence Dataset (RPSD) from https://ftp.dpb.carnegiescience.edu/rpsd/`
How can I get them?
Thanks

**Comment by bxuecarnegie** [comment]
Thanks for bringing this to our attention, the link is now fixed.

**Comment by Moo-cow** [comment]
Thank you! :)
