### ISSUE TITLE
RPSD cannot be downloaded

### ISSUE THREAD

**Issue by wen10-git** [carnegie/E2P2#11]
RPSD and PRIAM cannot be downloaded

hello @pokemonxue  @bxuecarnegie 

I cannot download RPSD (https://ftp.dpb.carnegiescience.edu/rpsd/) and PRIAM (http://priam.prabi.fr/) from the address on the description home page. No response after opening the web page.I can't open the web page. I don't know if it's my problem or the web page's. It won't open anyway. By the way I'm in mainland China.

**Comment by bxuecarnegie** [comment]
Hi,

The ftp website for the RPSD is maintained by us and still accessible (US). Unfortunately as of now the PRIAM website which is not maintained by us is indeed inaccessible. I've included a copy in the repository.

Best,
Bo

**Comment by wensulin93** [comment]
GREAT! @bxuecarnegi

But I repeatedly tried the URL https://ftp.dpb.carnegiescience.edu/rpsd/ (using the home network and school work network), and it was blank after entering, and no download link was prompted.  If it is convenient, please give me another download link or upload it as well?  Thanks!

![Uploading image.png…]()

**Comment by wen10-git** [comment]
GREAT! @bxuecarnegie 

But I repeatedly tried the URL https://ftp.dpb.carnegiescience.edu/rpsd/ (using the home network and school work network), and it was blank after entering, and no download link was prompted.  If it is convenient, please give me another download link or upload it as well?  Thanks!


![image](https://user-images.githubusercontent.com/63379795/199429355-fad8f411-b6fd-44fb-bad5-7601c98c4ffe.png)

**Comment by wen10-git** [comment]
I found a way to use the 3.1 version of the RPSD library, I hope it will be smooth. 

 By the way, version 3.1 is too slow because it cannot run multiple cores.  My data is relatively large, so this version 4.1 is more suitable.  At the same time, I still hope to get the download address of the latest RPSD?

**Comment by bxuecarnegie** [comment]
Unfortunately the RPSD is too large to upload to GitHub, based on the screen shot, it seems that you were able to access the website itself. Maybe there's some setting in your browser preventing the links to load up.

**Comment by XHHnefu** [comment]
> RPSD and PRIAM cannot be downloaded
> 
> hello @pokemonxue @bxuecarnegie
> 
> I cannot download RPSD (https://ftp.dpb.carnegiescience.edu/rpsd/) and PRIAM (http://priam.prabi.fr/) from the address on the description home page. No response after opening the web page.I can't open the web page. I don't know if it's my problem or the web page's. It won't open anyway. By the way I'm in mainland China.

In mainland China, this page seems not to be accessed.
