### ISSUE TITLE
Can't Download PRIAM_Search utility V2

### ISSUE THREAD

**Issue by danni-meme** [carnegie/E2P2#13]
Hi

I can`t download the software from the link you provided.

http://priam.prabi.fr/REL_JAN18/index_jan18.html

How can i get it?

Thank you

**Comment by bxuecarnegie** [comment]
Hello,

The website have been down for awhile. We've included a copy of  "PRIAM_search.jar" (https://github.com/carnegie/E2P2/blob/master/PRIAM_search.jar) in the repo.

Cheers,
Bo

**Comment by danni-meme** [comment]
Thank you! | ᐕ)⁾⁾
