### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by TanB003** [carnegie/E2P2#16]
Although I'm mentioning the whole path for the folder its still saying - can't find database at mentioned folder
![Screenshot from 2024-07-31 11-40-07](https://github.com/user-attachments/assets/e3e1b1c4-ee12-4a60-92d6-355b31b52838)

Kindly help!

**Comment by bxuecarnegie** [comment]
Due to the blastp path reading, you should include "/rpsd-4.2.fa" in your path

**Comment by TanB003** [comment]
Thank you for the quick reply!
