### ISSUE TITLE
Partial annotation results

### ISSUE THREAD

**Issue by anagonda-ai** [carnegie/E2P2#18]
Hello!
I am running e2p2 locally.
The input is fasta file with 11595 genes.
DeepEC_Results.txt contains only 3420 results.
What may be the reasons for that?
Thank you

**Comment by bxuecarnegie** [comment]
It's hard for me to judge your results with just the number of input and without an expected output. You can check the log folder of DeepEC and see if any of the intermediate output are empty which might indicate parts of the pipeline didn't run correctly.
Also Note that the DeepEC incorporated in E2P2 is a fork of the original pipeline and trained with our own RPSD so it's different to what you might expect if you're going with the original paper.

**Comment by anagonda-ai** [comment]
OK. Just saw that 3 category results are better, and enough for what I need. Thank you
