### ISSUE TITLE
evalue is not settable for blastp

### ISSUE THREAD

**Issue by lcottret** [carnegie/E2P2#3]
Hi, 

In the version 3.1 of e2p2, the evalue for blastp was set to 1e-2. 
In this version, the evalue is not set, i.e the default evalue (10) is considered.
Is it a choice ? 
(In the e2p2 v4 description in PlantCyc (https://www.plantcyc.org/about/documentation/e2p2-description), it's written  (BLAST, E-value cutoff <= 1e-2).)
In my version (lipm), I added an option "blast_evalue" with 10 as default value. If you're interested, I can do a pull request.

**Comment by bxuecarnegie** [comment]
Yes, we actually filter the by evalue through the python script due to a bizarre behavior of blast we keep encountering. There are missing hits if we set the cut off when running blastp.

**Comment by lcottret** [comment]
Ok, I understand better !  I see now where you filter by evalue, thanks ! I'm going to change my version so that it can be set by a parameter. Forget my last pull request.
