### ISSUE TITLE
singularity version of E2P2

### ISSUE THREAD

**Issue by lipme** [carnegie/E2P2#8]
Hi, 

I don't know where I can put this announcement: I just created a singularity file to install all the environment needed by e2p2. It clones the Master version of carnegie/e2p2:

https://github.com/lipme/e2p2-singularity 

Regards,
Ludo Cottret

**Comment by bxuecarnegie** [comment]
Hi Ludo,

Thanks for writing this version. I can put it under the 'Installation' segment of the README with your permission.

Best,
Bo

**Comment by lipme** [comment]
Hi,

Yes of course !

Regards,
Ludo

**Comment by bxuecarnegie** [comment]
Hi Ludo,

I've updated the README file and added your name in the Acknowledgement section. But feel free to push edits you see fit.

Best,
Bo
