### ISSUE TITLE
MetaCyc version

### ISSUE THREAD

**Issue by lcottret** [carnegie/E2P2#9]
Hi,

Which version of MetaCyc do you use ?
In the file https://github.com/carnegie/E2P2/blob/master/data/maps/pf-metacyc-RXN-EC.mapping, the version 21.5 is indicated.
But in https://github.com/carnegie/E2P2/blob/master/data/maps/efclasses.mapping, there are reaction ids (e.g  RXN0-1021) that are not in MetaCyc 21.5 but in the last version of PlantCyc.
Since I use the version 21.5 of the ptools, some reactions are not found during the automatic build...

Regards,
Ludo Cottret

**Comment by bxuecarnegie** [comment]
Yes, it includes both reactions from MetaCyc and PlantCyc, the PlantCyc was generated referencing the same version of MetaCyc. 

Best,
Bo

**Comment by lcottret** [comment]
Thanks. I have two other questions :
- This means that there are reactions in PlantCyc that don't exist in MetaCyc ?
- In order to use the pf file generated by E2P2, this means that we need to indicate PlantCyc as reference organism in the ptools ?

**Comment by bxuecarnegie** [comment]
1. To my knowledge, yes.
2. I haven't used pathologic in while, and although indicating "PLANT" in ptools is probably the best practice, I believe ptools itself would ignore reactions and pathways that aren't available.

**Comment by lcottret** [comment]
Hi ! 

Which version of PMN is used for reaction identifiers indicated in pf files generated by E2P2 ? It's to be sure to have the correct version of PlantCyc in my pathway-tools instance to indicate it as reference organism in the Pathologic pipeline...

**Comment by bxuecarnegie** [comment]
The RPSD 2019-03-07 released was generated using Metacyc 21.5 and Plantcyc 12.5
